name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: |
          uv venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          uv pip install ruff
          uv run ruff check .

      - name: Run tests
        run: |
          uv pip install pytest
          uv run pytest
